# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlateChat_Swift5' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PlateChat_Swift5

  #pod 'Firebase'
  #pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'Firebase/Functions'
  pod 'Firebase/Crashlytics'
  pod 'R.swift'#, '5.0.2'
  pod 'MessageKit', '1.0.0'
  #pod 'SwiftDate'
  pod 'RxSwift',    '~> 5'
  pod 'RxCocoa',    '~> 5'
  pod 'RxFirebase/Firestore'
  pod 'RxFirebase/RemoteConfig'
  pod 'RxFirebase/Database'
  pod 'RxFirebase/Storage'
  pod 'RxFirebase/Auth'
  pod 'RxFirebase/Functions'
  pod 'NSObject+Rx'
  pod 'Pageboy', '~> 2.0'
  pod 'Tabman', '~> 1.0'
  #pod 'PageMenu'
  #pod "PagingMenuController"
  pod 'SVProgressHUD', '2.0'
  #pod 'NVActivityIndicatorView'#, '4.3.0'
  pod 'SDWebImage', '4.3.3'
  pod 'DZNEmptyDataSet'
  #pod 'Nuke', '~> 6.0'
  #pod 'SKPhotoBrowser'
  pod 'SwiftMessages', '5.0.1'
  pod 'WARangeSlider'
  #pod 'RangeSeekSlider'
  #pod 'SwiftRangeSlider'
  pod 'SmileLock'
  pod 'THPinViewController', '~> 1.2.6'
  pod 'XLPagerTabStrip', '~> 8.0'
  pod 'Alamofire'
  pod 'SwiftDate'
  pod 'ReachabilitySwift'
  pod 'IQKeyboardManagerSwift'
  #pod 'Google-Mobile-Ads-SDK'
end


post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end
